# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7ffb5d9dd6cd5aae040cc9f132e3d3b271de27dde9ca1dbce9d796c5da9b3cb7fddc0bfa9374d94155a22aeae427aae01ec0fac64c95d639512b1d71a110f54

test:
  secret_key_base: 61562fbf91ff8a6c3c608cdf335aea6a56f3e6e6aa0ca6eedca2584cdc8cd159e586673e3c2393f2ca1175e93c362feba0feb255c6c2a1ab574e6984254ef0e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
